TrafoMaliyetHesap/Hesaplama.UI/Models/ErrorViewModel.cs
namespace Hesaplama.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TrafoMaliyetHesap/Hesaplama.UI/Models/HesaplamalarVM.cs
namespace Hesaplama.UI.Models
{
    public class HesaplamalarVM
    {
        public int Id { get; set; }
        public string ProjeNo { get; set; }
        public double Guc { get; set; }
        public double AGgerilim { get; set; }
        public double YGgerilim { get; set; }
        public double KazanGenislik { get; set; }
        public double KazanUzunluk { get; set; }
        public double KazanYukseklik { get; set; }
        public double Maliyet { get; set; }
    }
}

TrafoMaliyetHesap/Hesaplama.UI/Controllers/HesaplamaController.cs
using Hesaplama.DataLayer.Context;
using Hesaplama.DataLayer.Repositories.Interfaces.EntityTypeRepositories;
using Hesaplama.EntityLayer.Abstract;
using Hesaplama.EntityLayer.Concrete;
using Hesaplama.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Mapster;

namespace Hesaplama.UI.Controllers
{
    public class HesaplamaController : Controller
    {
        private readonly IHesaplamaRepository _hesaplamaRepository;
        private readonly ApplicationDbContext _context;

        public HesaplamaController(IHesaplamaRepository hesaplamaRepository, ApplicationDbContext context)
        {
            _hesaplamaRepository = hesaplamaRepository;
            _context = context;
        }

        public IActionResult Ekle()
        {
            return PartialView("_HesaplamaEklePartial");
        }
        [HttpPost]
        public IActionResult Ekle(HesaplamalarVM data)
        {
            if (ModelState.IsValid)
            {

                Hesaplamalar hesaplamalar = new Hesaplamalar();


                hesaplamalar.ProjeNo = data.ProjeNo;
                hesaplamalar.Guc = data.Guc;
                hesaplamalar.AGgerilim = data.AGgerilim;
                hesaplamalar.YGgerilim = data.YGgerilim;

                hesaplamalar.KazanUzunluk = data.KazanUzunluk;
                hesaplamalar.KazanGenislik = data.KazanGenislik;
                hesaplamalar.KazanYukseklik = data.KazanYukseklik;
                hesaplamalar.Maliyet = data.Maliyet;

                _hesaplamaRepository.Create(hesaplamalar);
                TempData["Success"] = "Hesaplama Ekleme Başarılı..!";
                return RedirectToAction("Liste");

            }
            return View(data);
        }
        public IActionResult Liste() => View(_hesaplamaRepository.GetByDefaults(x => x.Status != Status.Passive).OrderByDescending(x => x.CreateDate));

        public IActionResult Guncelle(int id)
        {
            Hesaplamalar hesaplamalar = _hesaplamaRepository.GetById(id);
            if (hesaplamalar != null)
            {
                HesaplamalarVM hesaplamalarVM = hesaplamalar.Adapt<HesaplamalarVM>();
                return PartialView("_HesaplamaGuncellePartial",hesaplamalarVM);
            }
            else
            {
                TempData["Warning"] = "Hesaplama Kaydı Bulunamadı..!";
                return RedirectToAction("Liste");
            }
        }
        [HttpPost]
        public IActionResult Guncelle(HesaplamalarVM data)
        {
            if (ModelState.IsValid)
            {
                Hesaplamalar hesaplamalar = _hesaplamaRepository.GetById(data.Id);
                if (hesaplamalar != null)
                {

                    hesaplamalar.ProjeNo = data.ProjeNo;
                    hesaplamalar.Guc = data.Guc;
                    hesaplamalar.AGgerilim = data.AGgerilim;
                    hesaplamalar.YGgerilim = data.YGgerilim;

                    hesaplamalar.KazanUzunluk = data.KazanUzunluk;
                    hesaplamalar.KazanGenislik = data.KazanGenislik;
                    hesaplamalar.KazanYukseklik = data.KazanYukseklik;
                    hesaplamalar.Maliyet = data.Maliyet;


                    _hesaplamaRepository.Update(hesaplamalar);
                    TempData["Success"] = "Hesaplama Güncelleme Başarılı..!";
                    return RedirectToAction("Liste");
                }
                else
                {
                    TempData["Warning"] = "Hesaplama Kaydı Bulunamadı";
                    return RedirectToAction("Liste");
                }
            }
            else
            {
                TempData["Error"] = "Hesaplama Kaydı Bulunamadı";
                return View(data);
            }
        }
        public IActionResult Sil(int id)
        {

            Hesaplamalar hesaplama = _hesaplamaRepository.GetById(id);
            if (hesaplama != null)
            {
                hesaplama.Status = Status.Passive;
                hesaplama.DeleteDate = DateTime.Now;
                _hesaplamaRepository.Delete(hesaplama);

                TempData["Success"] = "Hesaplama Kaydı Silindi..!";
                return RedirectToAction("Liste");
            }
            else
            {
                TempData["Error"] = "Hesaplama Kaydı Silinemedi..!";
                return RedirectToAction("Liste");
            }
        }
    }
}

TrafoMaliyetHesap/Hesaplama.UI/Controllers/HomeController.cs
using Hesaplama.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Hesaplama.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TrafoMaliyetHesap/Hesaplama.UI/Views/Hesaplama/Liste.cshtml
@model IEnumerable<Hesaplamalar>
@{
    ViewData["Title"] = "Liste";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="modalPlaceHolder" aria-hidden="true">
</div>
<div class="content-body">
    <div class="row">
        <div class="card col-md-12">
            <div class="card-header with-border">
                <div class="row">
                    <div class="col-md-12 d-flex">
                        <div class="col-md-8">
                            <h4 class="col-md-4">Trafo Maliyet Hesaplama Listesi</h4>
                        </div>
                        <div class="col-md-4">
                            <a class=" btn btn-sm waves-effect waves-light btn btn-primary mb-5 float-right text-white" id="btnEkle" style="float:right"><i class="fa fa-plus-square"></i> Hesaplama Ekle</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example" class="no-style-no no-style nowrap table-striped  table-hover table-compact display" style="width:100%;font-size:x-small">
                        <thead>
                            <tr>
                                <th>İŞLEMLER</th>
                                <th>ID</th>
                                <th>ROJE NO</th>
                                <th>GÜÇ</th>
                                <th>AG GERİLİM</th>
                                <th>YG GERİLİM</th>
                                <th>KAZAN GENİŞLİK</th>
                                <th>KAZAN UZUNLUK</th>
                                <th>KAZAN YÜKSEKLİK</th>
                                <th>MALİYET</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Hesaplamalar hesaplamalar in Model)
                            {
                                <tr>
                                    <td>
                                        <a data-id="@hesaplamalar.Id" class="btnGuncelle"><i class="fa fa-edit"></i></a>
                                        <a asp-action="Sil" asp-route-id="@hesaplamalar.Id" class="btn btn-sm btn-danger"><i class="far fa-trash-alt"></i></a>
                                    </td>
                                    <td>@hesaplamalar.Id</td>
                                    <td>@hesaplamalar.ProjeNo</td>
                                    <td>@hesaplamalar.Guc</td>
                                    <td>@hesaplamalar.AGgerilim</td>
                                    <td>@hesaplamalar.YGgerilim</td>
                                    <td>@hesaplamalar.KazanGenislik</td>
                                    <td>@hesaplamalar.KazanUzunluk</td>
                                    <td>@hesaplamalar.KazanYukseklik</td>
                                    <td>@hesaplamalar.Maliyet</td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>İŞLEMLER</th>
                                <th>ID</th>
                                <th>ROJE NO</th>
                                <th>GÜÇ</th>
                                <th>AG GERİLİM</th>
                                <th>YG GERİLİM</th>
                                <th>KAZAN GENİŞLİK</th>
                                <th>KAZAN UZUNLUK</th>
                                <th>KAZAN YÜKSEKLİK</th>
                                <th>MALİYET</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>
<!-- Datatable css-->
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.0.1/css/buttons.dataTables.min.css">
<!-- Datatable js -->
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.print.min.js"></script>

    @section Scripts{
        <script>
            $(document).ready(function () {
                // Setup - add a text input to each footer cell
                $('#example tfoot th ').each(function () {
                    var title = $(this).text();
                    $(this).html('<input type="text" style="font-weight:bold;align:left;text:black" placeholder=" ' + title + '" />');
                });

                // DataTable
                var table = $('#example').DataTable({
                    initComplete: function () {
                        // Apply the search
                        this.api()
                            .columns()
                            .every(function () {
                                var that = this;

                                $('input', this.footer()).on('keyup change clear', function () {
                                    if (that.search() !== this.value) {
                                        that.search(this.value).draw();
                                    }
                                });
                            });
                    },
                    language: {

                        info: "_TOTAL_ kayıttan _START_ - _END_ kayıt gösteriliyor.",
                        infoEmpty: "Gösterilecek hiç kayıt yok.",
                        loadingRecords: "Kayıtlar yükleniyor.",
                        zeroRecords: "Tablo boş",
                        search: "Arama:",
                        infoFiltered: "(toplam _MAX_ kayıttan filtrelenenler)",
                        lengthMenu: "Sayfada _MENU_  kayıt göster",
                        buttons: {
                            copyTitle: "Panoya kopyalandı.",
                            copySuccess: "Panoya %d satır kopyalandı",
                            copy: "Kopyala",
                            print: "Yazdır",
                        },

                        paginate: {
                            first: "İlk",
                            previous: "Önceki",
                            next: "Sonraki",
                            last: "Son"
                        },

                    },
                    responsive: true,
                    dom:
                        "<<'row'<'col-sm-4'l><'col-sm-6'B><'col-sm-2'f>><t>ip>",
                    lengthMenu: [
                        [5, 10, 25, 50, 100, 500, -1],
                        ['5', '10 ', '25 ', '50 ', '100', '500', 'Tümü']
                    ],
                    buttons: [
                        { extend: 'copy' },
                        { extend: 'excel', title: 'ExampleFile' },
                        { extend: 'pdf', title: 'ExampleFile' },

                        {
                            extend: 'print',
                            customize: function (win) {
                                $(win.document.body).addClass('white-bg');
                                $(win.document.body).css('font-size', '8px');

                                $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                            }
                        }
                    ],
                    scrollX: true,
                    scrollY: true,
                });


            });



            $(function () {
                const url = '@Url.Action("Ekle","Hesaplama")';
                const placeHolderDiv = $('#modalPlaceHolder');
                $('#btnEkle').click(function () {
                    $.get(url).done(function (data) {
                        placeHolderDiv.html(data);
                        placeHolderDiv.find(".modal").modal('show');
                    });
                });
            });

        $(function () {
            const url = '/Hesaplama/Guncelle';
            const placeHolderDiv = $('#modalPlaceHolder');
            $(document).on('click',
                '.btnGuncelle',
                function (event) {
                    event.preventDefault();
                    const id = $(this).attr('data-id');
                    $.get(url, { id: id }).done(function (data) {

                        placeHolderDiv.html(data);
                        placeHolderDiv.find('.modal').modal('show');
                    });
                });
        });

        </script>
    }

TrafoMaliyetHesap/Hesaplama.UI/Views/Hesaplama/_HesaplamaEklePartial.cshtml
@model HesaplamalarVM

<div class="modal fade" data-toggle="modal" role="dialog" area-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><strong>Hesaplama Ekle</strong></h5>
                @*                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Vazgeç">
                <span aria-hidden="true">×</span>
                </button>*@
            </div>
            <div class="modal-body">
                <form asp-action="Ekle" method="post" enctype="multipart/form-data">
                    <!--Cari bilgileri-->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-6">
                                <div class="form-group has-feedback">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label>Proje No</label>
                                        </div>
                                        <div class="col-md-9">
                                            <input asp-for="ProjeNo" id="inputProjeNo" class="form-control form-control-sm" type="text">
                                            <span asp-validation-for="ProjeNo" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="form-group has-feedback">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label>Güç</label>
                                        </div>
                                        <div class="col-md-9">
                                            <input asp-for="Guc" id="inputGuc" class="form-control form-control-sm" type="text">
                                            <span asp-validation-for="Guc" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="form-group has-feedback">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label>AG Gerilim</label>
                                        </div>
                                        <div class="col-md-9">
                                            <input asp-for="AGgerilim" id="inputAgGerilim" class="form-control form-control-sm" type="text">
                                            <span asp-validation-for="AGgerilim" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="form-group has-feedback">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label>YG Gerilim</label>
                                        </div>
                                        <div class="col-md-9">
                                            <input asp-for="YGgerilim" id="inputYgGerilim" class="form-control form-control-sm" type="text">
                                            <span asp-validation-for="YGgerilim" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br /><hr />
                            <div class="col-md-6 mt-2">
                                <div class="form-group has-feedback">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label>Kazan Uzunluk</label>
                                        </div>
                                        <div class="col-md-9">
                                            <input asp-for="KazanUzunluk" id="inputUzunluk" class="form-control form-control-sm" type="text">
                                            <span asp-validation-for="KazanUzunluk" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="form-group has-feedback">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label>Kazan Genişlik</label>
                                        </div>
                                        <div class="col-md-9">
                                            <input asp-for="KazanGenislik" id="inputGenislik" class="form-control form-control-sm" type="text">
                                            <span asp-validation-for="KazanGenislik" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mt-2">
                                <div class="form-group has-feedback">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label>Kazan Yükseklik</label>
                                        </div>
                                        <div class="col-md-9">
                                            <input asp-for="KazanYukseklik" id="inputYukseklik" class="form-control form-control-sm" type="text">
                                            <span asp-validation-for="KazanYukseklik" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 mt-2">
                            <div class="form-group has-feedback">
                                <div class="row">
                                    <div class="col-md-3">
                                        <label>Maliyet</label>
                                    </div>
                                    <div class="col-md-9">
                                        <input asp-for="Maliyet" id="inputMaliyet" class="form-control form-control-sm" type="text">
                                        <span asp-validation-for="Maliyet" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <input type="button" class="btn btn-block btn-primary mt-3" style="float: right;"
                               value="Hesapla" onclick="hesapla();">

                    </div><hr />
                    <!--Diğer bilgiler-->
                    <div class="row">

                        <div class="col-md-12">
                            <a href="/Hesaplama/Liste" class="btn btn-primary btn-sm"><i class="fa fa-backward"></i> Listeye Dön</a>
                            <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-save"></i> Kaydet</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    function hesapla() {

        var Guc
        var AgGerilim
        var YgGerilim
        var Genislik
        var Uzunluk
        var Yukseklik
        var Maliyet

        Guc = document.getElementById("inputGuc").value;
        AgGerilim = document.getElementById("inputAgGerilim").value;
        YgGerilim = document.getElementById("inputYgGerilim").value;
        Genislik = document.getElementById("inputGenislik").value;
        Uzunluk = document.getElementById("inputUzunluk").value;
        Yukseklik = document.getElementById("inputYukseklik").value;
        Maliyet = document.getElementById("inputMaliyet").value;


        var KazanGenislik = (Guc * AgGerilim) / 500;
        document.getElementById("inputGenislik").value = (KazanGenislik).toFixed(2).toString().replace('.', ',');

        var KazanUzunluk = (Guc * YgGerilim) / 10000;
        document.getElementById("inputUzunluk").value = (KazanUzunluk).toFixed(2).toString().replace('.', ',');

        var KazanYukseklik = ((KazanGenislik + KazanUzunluk) / AgGerilim) * 50;
        document.getElementById("inputYukseklik").value = (KazanYukseklik).toFixed(2).toString().replace('.', ',');

        var Maliyet = ((KazanGenislik * 1.5) + (KazanUzunluk * 1.25) + (KazanYukseklik));
        document.getElementById("inputMaliyet").value = (Maliyet).toFixed(2).toString().replace('.', ',');



        var inputGucDeger = Guc.toString().replace('.', ',');
        var inputAgGerilimDeger = AgGerilim.toString().replace('.', ',');
        var inputYgGerilimDeger = YgGerilim.toString().replace('.', ',');

        document.getElementById("inputGuc").value = inputGucDeger;
        document.getElementById("inputAgGerilim").value = inputAgGerilimDeger;
        document.getElementById("inputYgGerilim").value = inputYgGerilimDeger;


    }
</script>

TrafoMaliyetHesap/Hesaplama.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TrafoMaliyetHesap/Hesaplama.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>TRAFO MALİYET HESAPLAMA</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="#">MALİYET HESAPLAMA</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
@*        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>*@
        <!-- Navbar-->
@*        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>*@
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Geçmiş İşlemler</div>
                        <a class="nav-link" href="/Hesaplama/Liste">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Liste
                        </a>
                        
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
@*                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>*@
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/assets/demo/chart-area-demo.js"></script>
    <script src="~/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/js/datatables-simple-demo.js"></script>
    
    <div role="none" class="col-md-12 notifications notifications-position-top"><partial name="_NotificationPartial.cshtml" /></div>
    @RenderSection("Scripts", required: false)
</body>
</html>

    

TrafoMaliyetHesap/Hesaplama.UI/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
    <div id="toast-container" class="toast-container toast-bottom-right alert notification">
        <div class="toast toast-success" aria-live="polite">
            <div class="toast-title">İşlem Başarılı!</div>
            <div class="toast-message">@TempData["Success"]</div>
        </div>
    </div>

}

@if (TempData["Error"] != null)
{
    <div id="toast-container" class="toast-container toast-bottom-right alert notification">
        <div class="toast bg-danger" aria-live="polite">
            <div class="toast-title">İşlem Başarısız!</div>
            <div class="toast-message">@TempData["Error"]</div>
        </div>
    </div>
}

@if (TempData["Warning"] != null)
{
    <div id="toast-container" class="toast-container toast-bottom-right alert notification">
        <div class="toast toast-warning" aria-live="polite">
            <div class="toast-title">İşlem Başarısız!</div>
            <div class="toast-message">@TempData["Warning"]</div>
        </div>
    </div>
}